version: "3.9"

services:
  streamlit:
    build: .
    image: vbp_app
    container_name: vbp_app
    ports:
      - "8501:8501"
    restart: always
    command: >
      streamlit run app.py
      --server.port=8501
      --server.address=0.0.0.0
